/*
*  This file was automatically generated by bfi's compiler.
*
*  DO NOT EDIT THIS FILE DIRECTLY.
*  Any changes will be overwritten the next time this file is generated.
*
*  Copyright (c) 2026 Mazeed.
*/

#include<stdio.h>

static unsigned char tape[30000] = {0};
int main(){

char* restrict p = tape;
(*p)+=8;
while(*p) {
for (int i = 0; i < 1; ++i) ++p;
(*p)+=4;
while(*p) {
for (int i = 0; i < 1; ++i) ++p;
(*p)+=2;
for (int i = 0; i < 1; ++i) ++p;
(*p)+=3;
for (int i = 0; i < 1; ++i) ++p;
(*p)+=3;
for (int i = 0; i < 1; ++i) ++p;
(*p)+=1;
for (int i = 0; i < 4; ++i) --p;
(*p)-=1;
}
for (int i = 0; i < 1; ++i) ++p;
(*p)+=1;
for (int i = 0; i < 1; ++i) ++p;
(*p)+=1;
for (int i = 0; i < 1; ++i) ++p;
(*p)-=1;
for (int i = 0; i < 2; ++i) ++p;
(*p)+=1;
while(*p) {
for (int i = 0; i < 1; ++i) --p;
}
for (int i = 0; i < 1; ++i) --p;
(*p)-=1;
}
for (int i = 0; i < 2; ++i) ++p;
putchar(*p);
for (int i = 0; i < 1; ++i) ++p;
(*p)-=3;
putchar(*p);
(*p)+=7;
putchar(*p);
putchar(*p);
(*p)+=3;
putchar(*p);
for (int i = 0; i < 2; ++i) ++p;
putchar(*p);
for (int i = 0; i < 1; ++i) --p;
(*p)-=1;
putchar(*p);
for (int i = 0; i < 1; ++i) --p;
putchar(*p);
(*p)+=3;
putchar(*p);
(*p)-=6;
putchar(*p);
(*p)-=8;
putchar(*p);
for (int i = 0; i < 2; ++i) ++p;
(*p)+=1;
putchar(*p);
for (int i = 0; i < 1; ++i) ++p;
(*p)+=2;
putchar(*p);
return 0; 
}