/*
*  This file was automatically generated by bfi's compiler.
*
*  DO NOT EDIT THIS FILE DIRECTLY.
*  Any changes will be overwritten the next time this file is generated.
*
*  Copyright (c) 2026 Mazeed.
*/

#include<stdio.h>

static unsigned char tape[30000] = {0};
int main(){

char* restrict p = tape;
(*p)+=8;
while(*p) {
p+= 1;
(*p)+=1;
p+= 1;
(*p)+=4;
p-= 2;
(*p)-=1;
}
p+= 1;
(*p)+=2;
p+= 2;
(*p)+=1;
p-= 1;
while(*p) {
(*p)-=1;
while(*p) {
p+= 2;
(*p)+=1;
p-= 2;
(*p)-=1;
}
(*p)+=1;
p+= 2;
}
p+= 1;
(*p)+=1;
while(*p) {
(*p)-=1;
p-= 3;
while(*p) {
(*p)-=1;
p+= 1;
while(*p) {
(*p)+=1;
while(*p) {
(*p)-=1;
}
(*p)+=1;
p+= 1;
(*p)+=2;
p+= 3;
(*p)-=1;
p-= 2;
}
p-= 1;
while(*p) {
p-= 1;
}
p+= 2;
(*p)+=6;
while(*p) {
p-= 2;
(*p)+=5;
p+= 2;
(*p)-=1;
}
(*p)+=1;
p-= 2;
(*p)+=2;
putchar(*p);
while(*p) {
(*p)-=1;
}
p-= 2;
}
p+= 1;
putchar(*p);
p+= 1;
(*p)+=1;
while(*p) {
p+= 2;
}
p+= 1;
(*p)+=1;
}
return 0; 
}